baseUrl : https://kr.api.riotgames.com/
slack.incomming.webhooks.url :
lolImgUrl : http://ddragon.leagueoflegends.com/cdn/img/champion/splash/
victoryImg : https://github.com/elky84/loltracer/blob/master/assets/victory.png?raw=true
defeatImg : https://github.com/elky84/loltracer/blob/master/assets/defeat.png?raw=true
championJsonURL: http://ddragon.leagueoflegends.com/cdn/8.18.2/data/ko_KR/champion.json


logging:
  config: classpath:logback.xml
 
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  application:
    name: "@pom.artifactId@"
  jpa:
   generate-ddl: true
   show-sql: false
      
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/loltracer
    username:
    password: