baseUrl : https://kr.api.riotgames.com/
lineNotifyAccessToken : TVJPRINgQFSDzR6JThuDSNKcK1pGCbTKWCf1aBewpz2
lineNotifyUrl : https://notify-api.line.me/
lolImgUrl : http://ddragon.leagueoflegends.com/cdn/img/champion/splash/
victoryImg : https://github.com/elky84/loltracer/blob/master/assets/victory.png?raw=true
defeatImg : https://github.com/elky84/loltracer/blob/master/assets/defeat.png?raw=true

logging:
  config: classpath:logback.xml
 
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  application:
    name: "@pom.artifactId@"
  jpa:
   generate-ddl: true
   show-sql: false
      
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://172.30.1.34:3306/loltracer
    username:
    password: 

---

spring:
  profiles: production
  
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/loltracer
    username:
    password:
    tomcat:
     test-while-idle: true
     validation-query: SELECT 1
     initial-size: 10
     max-active: 20
     min-idle: 10
     max-idle: 10
     max-wait: 3000
     connection-properties: autoReconnect=true;useUnicode=true;characterEncoding=utf-8
logging:
  config: classpath:logback-production.xml