baseUrl : https://kr.api.riotgames.com/
slack:
  incomming:
    webhooks: 
      url: 
      channel: 
      icon-url: http://2.bp.blogspot.com/-HqSOKIIV59A/U8WP4WFW28I/AAAAAAAAT5U/qTSiV9UgvUY/s1600/icon.png
lolImgUrl : http://ddragon.leagueoflegends.com/cdn/img/champion/splash/
victoryImg : https://www.pngitem.com/pimgs/m/119-1199430_league-of-legends-victory-png-transparent-png.png
defeatImg : https://www.pngitem.com/pimgs/m/453-4539728_image-rights-to-riot-games-png-download-league.png
championJsonURL: http://ddragon.leagueoflegends.com/cdn/8.18.2/data/ko_KR/champion.json


logging:
  config: classpath:logback.xml
 
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  application:
    name: "@pom.artifactId@"
  jpa:
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/loltracer
    username: 
    password: 